### ISSUE TITLE
"Latest" gives errors

### ISSUE THREAD

**Issue by miriam-contentisbv-nl** [russorat/influxdb-action#6]
When I use the action as specified in the example it will result in an error

```
  - id: setup-influx-cli
    name: Setup InfluxDB Cli
    uses: influxdata/influxdb-action@v3
    with:
      influxdb_version: latest
      influxdb_start: false
```

results in
```
Run influxdata/influxdb-action@v3
Run export INFLUXDB_VERSION=latest
influxdb2_linux_amd64/README.md
influxdb2_linux_amd64/LICENSE
influxdb2_linux_amd64/influxd
cp: cannot stat 'influxdb2-2.7.1-linux-amd64/influxd': No such file or directory
rm: cannot remove 'influxdb2-2.7.1-linux-amd64/': No such file or directory
./
./LICENSE
./README.md
./influx
tar: .: Cannot utime: Operation not permitted
tar: .: Cannot change mode to rwx-----T: Operation not permitted
tar: Exiting with failure status due to previous errors
cp: cannot stat 'influxdb2-client-2.7.1-linux-amd64/influx': No such file or directory
rm: cannot remove 'influxdb2-client-2.7.1-linux-amd64/': No such file or directory
```
